using System.Security.Cryptography;
using PostQuantum.Cryptography;

// Computes SHA-256 fingerprints of public-key bytes that we derive from a
// known seed. These fingerprints anchor a regression-style KAT — if anything
// in the BCL or in our wrapper perturbs the deterministic seed → public-key
// mapping, the test that compares against these values will catch it.

static string Hash(byte[] data) =>
    Convert.ToHexString(SHA256.HashData(data)).ToLowerInvariant();

void EmitKem(string name, int seedSize, Func<byte[], MLKemPrivateKey> import)
{
    byte[] seed = new byte[seedSize];
    // Use a fixed, non-zero pattern: i % 256. All-zero would also work; this
    // exercises every seed byte being meaningful.
    for (int i = 0; i < seed.Length; i++) seed[i] = (byte)(i & 0xFF);

    using MLKemPrivateKey priv = import(seed);
    byte[] ek = priv.ExportEncapsulationKey();
    byte[] dk = priv.ExportDecapsulationKey();
    Console.WriteLine($"  // {name}");
    Console.WriteLine($"  public const string {name}_Seed = \"{Convert.ToHexString(seed).ToLowerInvariant()}\";");
    Console.WriteLine($"  public const string {name}_EncapsulationKeySha256 = \"{Hash(ek)}\";");
    Console.WriteLine($"  public const string {name}_DecapsulationKeySha256 = \"{Hash(dk)}\";");
}

void EmitDsa(string name, int seedSize, Func<byte[], MLDsaPrivateKey> import)
{
    byte[] seed = new byte[seedSize];
    for (int i = 0; i < seed.Length; i++) seed[i] = (byte)(i & 0xFF);

    using MLDsaPrivateKey priv = import(seed);
    byte[] pk = priv.ExportPublicKey();
    byte[] sk = priv.ExportSecretKey();
    Console.WriteLine($"  // {name}");
    Console.WriteLine($"  public const string {name}_Seed = \"{Convert.ToHexString(seed).ToLowerInvariant()}\";");
    Console.WriteLine($"  public const string {name}_PublicKeySha256 = \"{Hash(pk)}\";");
    Console.WriteLine($"  public const string {name}_SecretKeySha256 = \"{Hash(sk)}\";");
}

if (!MLKem.IsSupported || !MLDsa.IsSupported)
{
    Console.Error.WriteLine("This host does not expose ML-KEM/ML-DSA. Aborting.");
    return;
}

Console.WriteLine("// AUTO-GENERATED by tools/ComputeFingerprints. Do not edit by hand.");
Console.WriteLine();
EmitKem("MLKem512",  MLKem512.PrivateSeedSizeInBytes,  s => MLKem512.ImportPrivateSeed(s));
EmitKem("MLKem768",  MLKem768.PrivateSeedSizeInBytes,  s => MLKem768.ImportPrivateSeed(s));
EmitKem("MLKem1024", MLKem1024.PrivateSeedSizeInBytes, s => MLKem1024.ImportPrivateSeed(s));
EmitDsa("MLDsa44",   MLDsa44.PrivateSeedSizeInBytes,   s => MLDsa44.ImportPrivateSeed(s));
EmitDsa("MLDsa65",   MLDsa65.PrivateSeedSizeInBytes,   s => MLDsa65.ImportPrivateSeed(s));
EmitDsa("MLDsa87",   MLDsa87.PrivateSeedSizeInBytes,   s => MLDsa87.ImportPrivateSeed(s));

// X-Wing seed (32 bytes) → encapsulation key fingerprint
byte[] xseed = new byte[XWing.DecapsulationKeySizeInBytes];
for (int i = 0; i < xseed.Length; i++) xseed[i] = (byte)(i & 0xFF);
using XWingPrivateKey xpriv = XWing.ImportDecapsulationKey(xseed);
byte[] xek = xpriv.ExportEncapsulationKey();
Console.WriteLine($"  // XWing");
Console.WriteLine($"  public const string XWing_Seed = \"{Convert.ToHexString(xseed).ToLowerInvariant()}\";");
Console.WriteLine($"  public const string XWing_EncapsulationKeySha256 = \"{Hash(xek)}\";");
